Bump actions/checkout and actions/cache tags in Github Actions
MercuryTechnologies/string-variants pull request #2
Opened 2022-10-20 07:27 UTC by blx

Fixes deprecation warnings related to [Node 12](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/)

2022-10-31 16:31 UTC, lf- requested changes
This approach won't work: this is a generated file. You will have to contribute a fix upstream to haskell-ci :)

2023-01-11 04:32 UTC, blx commented
Upstream `haskell-ci` tracking reference: https://github.com/haskell-CI/haskell-ci/pull/602

2023-01-18 02:07 UTC, lf- approved these changes
i know i don't work here anymore but this looks good to me

2023-01-18 17:38 UTC, lykahb reviewed
Thanks for this change!

2023-01-18 17:39 UTC, lykahb approved these changes

2023-01-18 17:39 UTC, merged